---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
      - name: "app"
        image: "{{ .Values.app.imageName }}"
        command:
        - "python"
        - "-m"
        - "flask"
        - "run"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "{{ .Values.app.port }}"
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: {{ .Values.app.port }}
