---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector: 
    app: {{ .Chart.Name }}
  type: NodePort  
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: {{ .Values.app.nodePort }}
